Yes, you can view the contents of the Dockerfile that was used to build a Docker image. The Dockerfile is a text file that contains the instructions for building the image. It specifies the base image to use, the commands to run to set up the image, and any additional dependencies or configuration that is required.

To view the contents of a Dockerfile, you can use the docker history command to view the history of the image and see the commands that were used to build it. For example:

$ docker history <image-name>

This will display the history of the image, including the commands that were run to build it. You can then use the --no-trunc flag to see the full commands and the contents of the Dockerfile:

$ docker history --no-trunc <image-name>

Alternatively, if you have access to the source code for the image, you can find the Dockerfile in the root directory of the project.